name: Client code analysis and testing

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Go to client directory
        run: cd ./client

      - name: Install dependencies
        run: npm ci

      - name: Run eslint
        run: npm run lint

  formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Go to client directory
        run: cd ./client

      - name: Install dependencies
        run: npm ci

      - name: Run formatter check
        run: npm run formatting



     


